### ISSUE TITLE
[Feature Request] Multiple lines in details and state.

### ISSUE THREAD

**Issue by VisualTuber** [discordapp/discord-rpc#106]
Hello, i would like to suggest to make us able to have multiple lines in the details and state because if someone has no space to make the text they want to appear gets cut off because it doesn't fit then they wont be able to make what they want. Thank you.

**Comment by Emzi0767** [comment]
...and in English?

**Comment by xaanit** [comment]
"Hello, I would like to suggest that in Rich Presence you should be able to have multiple lines in the 'detail' and 'state' fields. If someone wants more text, it gets cut off and they can't do what they want. Thank you."

**Comment by VisualTuber** [comment]
Yeah that.

**Comment by msciotti** [comment]
Right now, the ellipsis is not how we want it. We might do a marquis on the text, but we won't support newline characters. We don't want really really really tall profile popouts because of a bunch of newline characters. It's also harder for users to quickly parse status information if some games' presence data looks wildly different from others.

I'd recommend you check out the [Best Practices](https://discordapp.com/developers/docs/rich-presence/best-practices) documentation. Strings should be short and pithy. Less is more in cases like these.

**Comment by VisualTuber** [comment]
But i need to show the stage that they are playing their score and their rapping status

**Comment by VisualTuber** [comment]
Anyways i'll try something else

**Comment by msciotti** [comment]
I would recommend maybe using `state` for the status, `details` for the current score, and using the `largeImageText` aka the tooltip on the large image to show stage/map. You get all your data there, have some nice artwork, and it's much easier to parse.

**Comment by VisualTuber** [comment]
I did that already :P

**Comment by VisualTuber** [comment]
![default](https://user-images.githubusercontent.com/30368284/34909810-d463ed60-f8b0-11e7-9bd9-7834834a6d12.png)
