### ISSUE TITLE
Unity setup issues

### ISSUE THREAD

**Issue by dylanh724** [discordapp/discord-rpc#150]
The readme seems very Linux/C++ centric, not showing much direction in regards to use with Unity. I could use some clarification. Here is what I've done:

1. Install Python for Windows, pip, and 'click' for pip.
2. ...I ended up skipping the build stuff since I couldn't get the script to work (kept getting 'missing file') and just jumped to 'release' for the DLL
3. I grabbed copied /x64-dynamic/bin/**discord-rpc.dll** (to be pasted later)
4. I copied...
```
[..]/examples/button-clicker/Assets/*
```
to
```
/MyUnityProject/Assets/Discord/
```
5. I also pasted the aforementioned DLL to /Discord/
6. I can load up the Unity scene and have Discord init fine. However, it says build failed.
7. Opening up **BuildHelper:30** it's looking for `../../discord-build.py` 
(where does `../../` lead to (as in: Where does this process **start** from? I'll Google this and get back. +Should probably set this to project root since the docs don't specify this needs to be in very specific spot)
8. I tried moving **discord-build.py** to /MyUnityProject/ project root, but that didn't help. **What else is needed at root? I thought I just needed the dll~**. 

I could't find any of these steps in the docs, so just playing a lot of this by ear. I couldn't find anything on Google about a Unity setup, either, so if you guys can help me fill in some blanks I can make a quickstart video or something.

**Comment by msciotti** [comment]
Hi Dylan. Yes, the README is C++ centric, as the SDK is written in C++. The `BuildHelper.cs` file is specific to the Unity example in our repo—which is why it's under examples and not the source files—and it just moves the DLLs into the proper `Assets/Plugins` folders. If you want to change the folder structure of your own project, it's not a great idea to copy and paste our example into your code. You should grab the `DiscordRpc.cs` file and use it like a header file for the SDK. The SDK itself goes where plugins normally go in Unity, `../Plugins/x86` and `../Plugins/x86_64`.

I'm also not sure where this `discord-build.py` script is coming from. I don't see that reference anywhere in the code.

**Comment by dylanh724** [comment]
Hey this helps a ton, thanks! 

> I'm also not sure where this discord-build.py script is coming from. I don't see that reference anywhere in the code.

Diving further, it seems to check for the dlls starting at **BuildHelper.cs:55** -- then calls **RunRpcBuildScript()** if it can't find it, outputting `Build Failed` if it can't find the .py file.

Thanks for the help; I'll poke around!
