### ISSUE TITLE
No default images are showing (non-default works np)

### ISSUE THREAD

**Issue by dylanh724** [discordapp/discord-rpc#151]
Possibly Related: https://github.com/discordapp/discord-rpc/issues/21

![image](https://user-images.githubusercontent.com/8840024/37651306-aea21e30-2c72-11e8-9f6e-7800000ee1a7.png)

The default image is uploaded, but nada ~ I tried disabling the cache and refreshing. Still nothing.

Any ideas?

**EDIT 1:** Tried uploading pictures and naming them -- this works. Default does not~

**Comment by msciotti** [comment]
That default image is just used for the invite embeds, as shown by the image preview next to the uploader.

![image](https://user-images.githubusercontent.com/4193854/37670822-856ebcbc-2c27-11e8-80ba-6685cb924f15.png)

The copy could probably use some work to explain this more clearly, but that's why!
