### ISSUE TITLE
Fails to compile with GCC 8

### ISSUE THREAD

**Issue by E5ten** [discordapp/discord-rpc#172]
https://hastebin.com/etokunecux.rb
compiles successfully if I downgrade to GCC 7.

**Comment by parkerlreed** [comment]
Same here on 8.1.0 on Arch.

**Comment by lodi-g** [comment]
You can `reinterpret_cast<void *>` both dest and src on the memcpy.

That's a workaround.

**Comment by msciotti** [comment]
I will admit I don't know enough about compilers to solve this 😁 maybe @snowyote can weigh on on a possible solution, or if you have one that you can PR, please do!

**Comment by lodi-g** [comment]
The actual problem is in the `rapidjson` dependency (see [this issue](https://github.com/Tencent/rapidjson/issues/1205)).

GCC recently added to G++ a warning when `objects of non-trivial class types are manipulated in potentially unsafe ways by raw memory functions such as memcpy, or realloc.` ([see changelog](https://gcc.gnu.org/gcc-8/changes.html)).

So the solution would be to explicitly cast the pointers do `void *`, allowing `memcpy` to do its job.

**Comment by msciotti** [comment]
Ah, OK. Thank you for that info!

**Comment by Antidote** [comment]
This failure is caused by `-Werror`, I recommend removing this as that is an option designed to fix issues before shipping a product out of the door, it's currently causing my own project to fail due to your project failing with this particular error. 

Keeping `-Wpedantic` is perfectly sane, but thrusting `-Werror` on outside projects is rather presumptuous.

**Comment by msciotti** [comment]
@Antidote do you mean in our CMake files?

https://github.com/discordapp/discord-rpc/blob/d279c24c6ad040a2ae75f6e003e6547873092b12/src/CMakeLists.txt#L74-L89

this?

**Comment by Antidote** [comment]
Yes, I mean in your CMakeLists.txt.

**Comment by lodi-g** [comment]
I'd say Werror is a decent choice in such a project though?

**Comment by Antidote** [comment]
I disagree, you should not negatively affect outside projects, ever.

**Comment by msciotti** [comment]
I don't have enough knowledge to understand ramifications of that change, so I will defer to @snowyote on this proposal.

**Comment by Antidote** [comment]
To mitigate this you could add an option to enable `-Werror` rather than removing it entirely.

**Comment by night** [comment]
> but thrusting `-Werror` on outside projects is rather presumptuous.

I don't share an opinion on this, but we offer prebuilt binaries for outside projects to consume this library, so I'm not sure how we're exactly "thrusting" this compilation error on you. the purpose of open sourcing this iirc was so external users could contribute back to the project and also implement similar functionality via their own libraries if they so desired.

**Comment by E5ten** [comment]
I don't understand why it wouldn't just be an option that defaults to off given that it causes some issues elsewhere, that seems like win win.

**Comment by E5ten** [comment]
I assume that's just making the flag disabled by default, I already compiled it but just manuall removed the flag a bit less than an hour ago and it worked.
