### ISSUE TITLE
Have websocket connections been forgotten about?

### ISSUE THREAD

**Issue by Velkon** [discordapp/discord-rpc#225]
Currently the [docs for setting up a websocket rpc connection](https://discordapp.com/developers/docs/topics/rpc#connecting) state to whitelist an rpc origin, but there is no way to do that in your [application settings](https://discordapp.com/developers/applications/).

The Discord client seems to check for rpc_origins in the app's json when you connect, but I can't find any way to set them on my app. So all sockets get closed due to having an invalid origin.

![https://i.imgur.com/HFFjWiu.png](https://i.imgur.com/HFFjWiu.png)

I realize that RPC used to be whitelisted through the Gamebridge program but that seems to have [disappeared as it's a 404 now](https://discordapp.com/gamebridge). Since anyone can use IPC, is WSS just lost forever?

I don't know if I'm misinformed or if I missed an update, but any info on getting Web-socket connections working would be useful. 
Thanks for reading

**Comment by CharlotteDunois** [comment]
Looks like this comment is still valid. https://github.com/discordapp/discord-rpc/issues/192#issuecomment-395514108

**Comment by msciotti** [comment]
Charlotte is correct. WebSocket connections are not currently supported for interfacing with Discord for Rich Presence functionality; you'll need to use IPC or RPC. We removed the GameBridge marketing material a while ago, as it's since been deprecated.

If you have a local application, connecting via RPC shouldn't be an issue. However, if you're trying to do something like connecting from a browser, it will fail. We've whitelisted the Rich Presence commands over RPC/IPC to not require auth, but they do require you to _not_ have an origin header, as we don't want arbitrary websites opening connections to Discord.
