### ISSUE TITLE
Timestamp Inconsistency - Seconds vs Milliseconds

### ISSUE THREAD

**Issue by Lachee** [discordapp/discord-rpc#231]
## Problem
Discord requires seconds for timestamps but violates this on its response and returns milliseconds instead

## Details
When you send a timestamp presence to discord, you send the time in unix epoch seconds. This allows for a simple conversion for what ever language you use. However, when you listen to the emit messages for confirmation and syncing of presence, discord will fill the timestamp in milliseconds instead.

This can cause overflow issues on some system and results with inconsistent and confusing code. (See timestamp conversion [here](https://github.com/Lachee/discord-rpc-csharp/blob/master/Discord%20RPC/RichPresence.cs#L547)). This is similar issue to discord returning asset hashes instead of asset keys on the presence emit.

## Reproduction
1. Send a SET_ACTIVITY with start timestamp set to current unix seconds. 
2. Look at response in either pipe messages or in discord console
3. Notice there are 3 extra 0s at the end of the timestamp.

**Comment by MinnDevelopment** [comment]
The decision to use seconds in the SDK was made while the API was still under development. They decided to go with millis. later but could not change it for the SDK (and ipc layer) anymore as that would be breaking backwards compatibility for the library user. If they would have updated it to millis all users of the library would be forced to update the SDK in their codebase and their use of timestamps which would've been a big inconvenience and an even bigger one now. The reason they probably use millis. timestamps came along with other services such as spotify and twitch making use of the rich presence, however can provide millis. precision.

Note that changing the received presence to seconds would also be a breaking change for all the bot libraries and the client as both expect millis. to be used now.

Fun fact: in the very beginning they were actually sending the timestamps as floats in the gateway events

**Comment by Lachee** [comment]
I don’t see how this response being changed will effect much. Since the sending is in seconds already, applications like Spotify won’t have to change. In theory this is only a change to how libraries listen to the set presence confirmations sent by discord. 

I can understand the reluctance to change however if it is the basis of the game sdk with how it emits timestamps in general and how the change either way would break consistency between the sdk and rp if only the rp response was changed, however I feel it’s more important to get consistence between what you are sending and what you are getting back.

**Comment by MinnDevelopment** [comment]
>I don’t see how this response being changed will effect much

It is affecting every library that was built to receive these payloads. They all will collectively fail to then properly parse the timestamps simply because it is a change the protocol that is not backwards compatible. This would cause a lot of confusion among library users that would get completely wrong timestamps as well as library devs that have to update their handling.

**Comment by msciotti** [comment]
You are both correct in the fact that sending seconds and returning milliseconds kinda sucks, but also it's not something we can really change right now. We use the milliseconds internally, so if anything, we'd need to change the SDK to send in milliseconds rather than seconds. And, as Minn pointed out, that means all SDK users would need to update. Unless we do some hacky stuff to support both.

You're right that it's not ideal, and I'm sorry about that. Realistically this is just a pain point for folks that have gone above and beyond to roll their own wrappers and do stuff like confirmation of presence updates, as that doesn't happen in the SDK itself. It sucks that it's worse for folks like you, but it's not a simple change right now.

I'll keep track of this with a ticket, because we _should_ figure out a way to make this consistent somehow, but it's fairly low priority as it doesn't break anything with the official SDK, and anyone implementing this themselves over IPC/RPC/whatever is already in the wilderness on this stuff.

**Comment by msciotti** [comment]
Update—we'll do this in a slightly hacky way within Discord itself, so we can support both being sent from the SDK. I've got a ticket to track this and mentioned back here when it's completed.

**Comment by msciotti** [comment]
Change is in master! I can ping back here when deployed.

**Comment by msciotti** [comment]
This should be all set now!
