### ISSUE TITLE
[Feature Request] Non RPC/IPC connection method for alternative platforms (mobile, console, etc.)

### ISSUE THREAD

**Issue by fr500** [discordapp/discord-rpc#237]
Hi

I worked on the RetroArch integration.
Do you provide any API to update discord on platforms without RPC/IPC?

A webservice or a HTTP api?

**Comment by fr500** [comment]
I guess it could be done on LAN talking to a local client
https://discordapp.com/developers/docs/topics/rpc#setactivity

**Comment by Lachee** [comment]
They did have a http based api for a while but took it down because it wasn’t able to detect presence of the application properly. It was unable to use the main feature of rp too, which was the join and spectate feature since https can’t be used for real-time events easily.

**Comment by fr500** [comment]
Awww sucks..
Thanks for the heads up anyway 👍

**Comment by msciotti** [comment]
Hey there!

We don't have any plans to do Rich Presence without a local socket connection right now. It's something that's been requested a bit, but we'd need to make some changes on our end. We don't want, for example, a random website to be able to open up a WebSocket to your local Discord client and start sending presence.

With a downloaded app, there's an implicit permission since you downloaded the app to your computer.

We'd probably need to do some oauth stuff with a special scope to say "Hey this website/webgame/whatever wants to update your presence". But it's not scoped right now, and may not be something that we'd even want to expose.

Is there an issue with using RPC/IPC? I know RetroArch is a locally downloaded program, so you shouldn't hit problems there?

**Comment by fr500** [comment]
@msciotti thanks for replying.
Well the problem is... we're on PC, but also switch, android, iOS, WiiU, Switch, Vita, PS3, XBOX360, etc, etc, etc 

So yeah no clients there.
We have been thinking about making a proxy of sorts (so the user would have to setup discord and the proxy on his PC to use RPC)

**Comment by msciotti** [comment]
Ah, yeah, I see. Yeah we do not currently have a solve for multi-platform stuff like that.

Also, impressive. Yeah, the PC Proxy thing is the immediate solve, understanding it's a bit meh.

I think I lost the ticket for tracking this when we briefly had HTTP API stuff, so I can turn this back into that feature request.

**Comment by Lachee** [comment]
The original request was issue #191 . But since it was a bug at the time I suppose it closed down.

**Comment by msciotti** [comment]
@Lachee understood. It's sort of a two-fold issue. There's the request to expand Rich Presence support to other stateful methods—like plain old WebSocket—and also the request to make it work with stateless stuff like HTTP, as it briefly did.

I think this issue well enough captures the sentiment of "give us more ways to do this please!", so I'll keep it up as the feature request.

**Comment by fr500** [comment]
Thanks for keeping an open mind about it.

**Comment by msciotti** [comment]
Moved to [Feedback Site](https://support-dev.discordapp.com/hc/en-us/community/posts/360043426071-Non-RPC-IPC-connection-method-for-alternative-platforms-mobile-console-etc-) as a part of #290
