### ISSUE TITLE
Discord C++ RPC Is Not Working For No Reason

### ISSUE THREAD

**Issue by leungyauming** [discordapp/discord-rpc#296]
Although I have been following the instructions in the official documents, but Discord is not showing up the game status. 
Github repo link:  https://github.com/mercode-org/mercode-discord-rpc-cpp

**Comment by msciotti** [comment]
Hey there. Not sure if that link is a private repo or has since changed, but I cannot view it. Discord not showing game status can be a few things; I'd recommend making sure you've got error callbacks properly hooked up to check for any error codes.

You can also open the chromium console in Discord by pressing control + shift + i and looking for any logs prefixed with `[IPC]` . Those will be messages to and from your game via the SDK and might alert you to any errors.

**Comment by msciotti** [comment]
Closing this issue due to deprecation of the repo and lack of comments on this issue. If you still are having problems, please move to the Game SDK here: https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide

If you'd like help with the Game SDK, come pay us a visit at discord.gg/discord-gamesdk !
