### ISSUE TITLE
Unity Example does not connect to discord

### ISSUE THREAD

**Issue by ruff-fighterbase** [discordapp/discord-rpc#36]
When launching Unity example it shows in log:

"Discord: init", 
"Discord: on click!"

On exit: "Discord: shutdown"

No message "Discord: ready". It shows also "Discord Disconnected". No other messages or errors in log.
Tried from latest master, also tried library replacement from released archive zip - the same result

**Comment by msciotti** [comment]
Hey @ruff-fighterbase—you may need to manually add Unity to your game detection in Discord for this to connect properly. The sample application is running off Unity's process id, so if Discord doesn't know it should be looking for that, it won't know that your game has connected.

In the future, we hope to improve this so that games that connect over RPC automagically are detected.

Let me know if this solution works for you.

**Comment by ruff-fighterbase** [comment]
Hey @msciotti, could you please send me instructions how to setup that?
I tried with application provided in sample, Application id 345229890980937739

Also I can create and setup new application in Discord

**Comment by msciotti** [comment]
@ruff-fighterbase it's in your Games settings in Discord:

![screen shot 2017-11-15 at 10 01 48 am](https://user-images.githubusercontent.com/4193854/32852195-0d243cd4-c9ec-11e7-84c3-d6e086c5c2ea.png)

Once you select Unity from that dropdown list, the SDK should properly connect, and it will show the test data when you click the button in Unity.

**Comment by ruff-fighterbase** [comment]
Wow, it works! Thank you, @msciotti 
(the steps: install desktop version of Discord, launch Discord, launch Unity, add Unity application as a game in Discord "Games" session and then restart Unity sample)
