### ISSUE TITLE
[Feature Request] Dynamically Set Application name

### ISSUE THREAD

**Issue by Kraust** [discordapp/discord-rpc#54]
I noticed that Rich Presence does not support a custom App Name (as in "Now Playing ..."). It instead takes the App Name from the Application Name from under https://discordapp.com/developers/. Is it planned in the future to allow the developer to set the App Name? I would like to create a dynamic App Name for something that I am working on.

**Comment by crmarsh** [comment]
We didn't plan on having that.. what are you working on that would use that? It sounds like it would just be confusing. Why not just set the state and/or details string?

**Comment by Kraust** [comment]
I am currently working on an application that bridges both Kodi's JSON-RPC and Discord's Rich Presence. This would allow users to display their "Playing" status from Kodi in Discord. I would *prefer* to dynamically set the "Playing" status to whatever the user is Playing (e.g. a song title) instead of the name of my Application. In the future this may also be extended to work on other applications that *aren't* Kodi, and don't already have Rich Presence Support. 

Of course its understandable if Discord is keeping the App name static as a security measure. I would have also preferred to set the larger image thumbnail to a custom image as well (e.g. for an Album Cover).

**Comment by tilda** [comment]
I don't think you can do custom images.
Images are keys from the Rich Presence application. Like if I add `image_large`, I use it like `{ 'large_image': 'image_large' }`. 
So unless you add the album art for your (music/movie/video) library and use the image keys when they're being played, I don't think you can really do it (especially since it's limited to 150 images).
What you could really do is just display a Kodi logo or something.

**Comment by Almighty-Alpaca** [comment]
I've written a plugin for all Jetbrains IDEs. Currently it always shows `IntelliJ` as game but it would be nice to set the name of the IDE the plugin is currently installed on. Currently there is no way to achieve that without creating 15 applications, one for each IDE, wich is not only very ugly but also is above the limit of application per account.

**Comment by msciotti** [comment]
I'm not sure if we're going to support this, but we hear your use cases. I'm going to leave this issue open as the official "We want dynamic app names" request and de-dupe other requests into this one.

**Comment by SlySven** [comment]
Can I also mention a slightly atypical case which could benefit from this: the application I am working on is a MUD client and it would be nice if we could display the name of the MUD server that our users are connected to and are playing on alongside our application name.

Admittedly this requirement will eventually be mitigated because once MUD Servers themselves grow their own Discord guilds they and us (and hopefully other MUD clients) can agree some protocols over "standard" icon names/purposes and - with their application IDs we can provide a "Rich Presence" pass-through and package/modules/scripts to link our users state to what gets shown when they are playing on the MUD server...

**Comment by msciotti** [comment]
The second part of your comment, @SlySven, is correct in that if they're all tied to the parent application id, asset slots are limited.

However, you can easily display both the server name and your application name. Your application's name will be at the top as "Playing <x>". You could use the `details` string to note which specific MUD they're playing from there.

**Comment by SlySven** [comment]
@msciotti - yeah that is the current proposal - but I want the originator of that (a co-coder) to consider replacing "Playing XXXX" with something shorter:
![screenshot_2018-06-25_03-16-30](https://user-images.githubusercontent.com/6163092/42061447-2588bd1c-7b22-11e8-9f61-33b21ddf1e4d.png)

What this proposal would do would enable the project that I am coding for to merge the "**Mudlet**" line with the "Playing MidMUD" so that the first, **BOLD** line of text, to the right of the large icon, could be something like "**MidMUD using Mudlet**" {"Mudlet" being the Client I am coding for/on and "MidMUD" the current Server (Game) that it is connected to} and save the **Details** line for some, er, *game state* details.

*BTW This is for MUD Servers that do not themselves have Discord Guilds/Servers with `APPLICATION_ID`s that have been provided to us.  If they* have *furnished that detail then we could access **their** Icon resources that they have told us about - and in* **that** *situation we could change from being whatever the name they used when creating the APPLICATION_ID {Say "MidMUD" for instance} - to seamlessly also reflect the situation of "**MidMUD using Mudlet**"!* - That is partly dependent though on another issue, which I will mention when I have filed it.

**Comment by wr1ght** [comment]
Any updates on this feature? Looking to do something similar as OP. Tried messy ways such as updating the application name if the song name doesn't match the application name, required me to re-connect everytime so the name would update on the presence. (plus, I don't really think that was a good idea)

**Comment by msciotti** [comment]
Moved to [Feeback Site](https://support-dev.discordapp.com/hc/en-us/community/posts/360043629592-Dynamically-set-application-name) as part of #290

**Comment by VelocityRa** [comment]
> Moved to [Feeback Site](https://support-dev.discordapp.com/hc/en-us/community/posts/360043629592-Dynamically-set-application-name) as part of #290

Bump?
Also the above link is dead.

> We didn't plan on having that.. what are you working on that would use that? It sounds like it would just be confusing. Why not just set the state and/or details string?

Because no-one actually clicks on profiles, to see rich presence details.
As others said this is useful for music/movies etc app rich presence support.
There it's the difference between 99% of people seeing ie. "Playing <song title/artist>" instead of "Playing Music" or such.

I think this should be re-opened.

**Comment by 1upbyte** [comment]
Even the native Spotify integration suffers from this. The status is set to Listening to Spotify rather than Listening to <song>.

**Comment by Kraust** [comment]
Pretty crazy that after 5 years a feature that MSN messenger supported is still unsupported within Discord's API.

Of course, this API is deprecated and I'm guessing something else already implements it.

**Comment by VelocityRa** [comment]
Opened a new issue. #375
