### ISSUE TITLE
[Request] Function to send callback to party host that joining player has loaded app and is ready.

### ISSUE THREAD

**Issue by StrikerMan780** [discordapp/discord-rpc#62]
In my frontend for Duke3D, I would like a way for joining players to able to signal to the host that they've managed to launch the app and are ready (something like Discord_JoinCompleted() that I can stick in joinGame somewhere), so that the host running the frontend can increment the party size accordingly at the appropriate time, and close the app if the party size is reached. (As by then the frontend would launch the game already, and is no longer needed).

Reason I ask this, is I can't increment the party size in the joinRequest callback, as it can cause a race condition, where the party is signaled as being full, or the frontend quits before the joining player's discord acknowledges that they've been accepted into the match, cancelling the join request for them. I *could* create my own signal back through winsocks, or some other socket library, but that is a royal pain.

The last option is just not updating the party size, and keeping the frontend running while the game itself is waiting for connections, but that allows people to attempt joining when the party is already full and the game is in progress, which is far from good. (And what I'm doing right now just to make it usable.)

Lastly, I'd like an equivalent of "joinRequest" when players just join through invites. Just so I can update the state of the frontend when people join.

**Comment by night** [comment]
I would say you shouldn't assume a party spot to be filled if an invite is sent in response to a request to join. A request to join is not really a confirmation that the user will join the party, moreso that they would like an invite to join.

But, doing this should still be possible without any modifications on our end. Once an invite is sent the client can join at any point in the future, but you can temporarily add that user to the party on your matchmaking service to save a spot for them when an invite is sent. You can then set a timeout on their spot (if they don't join during that time you give up their spot and their invite is no longer guaranteed). Your matchmaking service will know when someone actually joins the party, so a callback should not be needed. Simply incrementing the party size is really not enough as you said since you cannot tie that spot to the user requesting and the party could fill up.

**Comment by StrikerMan780** [comment]
This is a frontend, it does no actual networking itself, joining players do not connect with my program, but another one.

**Comment by crmarsh** [comment]
I still think it is weird that you are not doing any networking in your multiplayer lobby frontend. It seems like you want to do networking indirectly via Discord rpc, but that's not really what this is for (though maybe we could do that at some point).

**Comment by StrikerMan780** [comment]
*heavy annoyed sigh*

**Comment by dylanh724** [comment]
Not sure why this is closed, it's a legit feature request and makes sense. In even one real-use scenario, the callback will tell the host to WAIT for them -- that he's joining. The game has to launch, he has to login, load everything up, he could have a trashtop laptop taking ages, or simply taking his time...

A second reason is to determine if we should RESERVE the slot for the guy joining or not. 

A third is for sanity reasons - eliminates the redundant "are you coming or not?" message.

**Comment by msciotti** [comment]
Well, @dylanh724 these are slightly different requests. Striker was looking for something to signal that the client had already successfully launched the app and was just awaiting the actual joining part.

I think there may be a legit use case in an event like `ACTIVITY_JOIN_INVITE_ACCEPTED`. This would fire back to the person who sent the invite to let them know that:

A. Someone has clicked on an invite in chat
B. The person who asked to join the game is launching the game after you've approved their ask

I think _that_ is a legit use case.
