### ISSUE TITLE
Windows XP "support"

### ISSUE THREAD

**Issue by YaLTeR** [discordapp/discord-rpc#83]
Yes, I know, Windows XP, EOL and whatnot, but my game supports Windows XP and some people for whatever reason still play on Windows XP. I link discord-rpc statically and due to its [usage of the `RegSetKeyValueW` API call](https://github.com/discordapp/discord-rpc/blob/master/src/discord_register_win.cpp#L61) the game fails to start.

Perhaps it's possible to replace it with a call that exists on Windows XP, or load it dynamically? This would also allow to get rid of the MINGW Vista defines at the top of that file.

If this is out of scope of this repository, I'll come up with something myself.

**Comment by msciotti** [comment]
While a valid use case, Discord unfortunately does not support Windows XP in an official or unofficial capacity. Apologies that we can't offer more help with it, but we won't change the SDK for non-supported Windows versions.

**Comment by YaLTeR** [comment]
Alright, I understand, thanks for the response.

**Comment by Solybum** [comment]
I encountered this issue as well.
Due to the registry functions, it's not possible to use the library in XP.

@msciotti I don't think it needs and SDK changes, in fact I built it in VS2017, SDK 10.0.16299.0, Toolset v141 (not the xp support variant) and it works fine in XP. 
(The library that the game interacts with is built with xp toolset).

The discord code is not used in XP given the fact that discord won't run in XP, but at least this allows the game to run in XP with discord rpc statically linked.


[Here](https://github.com/Solybum/DiscordRPC/blob/master/DiscordRPC/discord_register_win.cpp#L51)

**Comment by msciotti** [comment]
@Solybum appreciate your linking your fix. If you're interested, I'd be happy to have you PR that logic in a conditional block to at least allow people to run their games on Windows XP without the SDK being a blocker.

**Comment by Solybum** [comment]
Do you think it would be ok to just change the registry functions to their older variant without any conditional compilation?

As per the comment at the beginning of the file.
> some of functions used here require WINNT >= 6.0 APIs
Such API is e.g. RegSetKeyValueW.

However, RegOpenKeyExW and RegSetValueExW should work here too.
The problem is that linking the library on a different project with XP support won't be able to find the functions currently used.

**Comment by Emzi0767** [comment]
Windows XP is dead. Having a computer running XP connected to the internet is nothing but irresponsible. Nobody will go any extra mile to fix an issue with an operating system this old.

You should tell your users to move to an operating system that is not 16 years old. If you really want to support XP, fork the repo, make the changes yourself, and distribute your modified version of the library. But that's a waste of effort in my opinion.
